### ISSUE TITLE
can you simplify this line ?

### ISSUE THREAD

**Issue by sidsm009** [Tiwarishashwat/InterviewCodes#1]
Hi @Tiwarishashwat , could you please simplify this line in your code - it will be very helpful for faster understanding of the code.

I have seen your video on youtube (https://www.youtube.com/watch?v=MPzgnmH3tOg) and it is really helpful. Yet, this part of the code is bit confusing. :-). By using appropriate line comments, and self-explanatory variable names, it will be easier for your subscribers to get better understanding of the solution which you explained.
Thanks in advance. :-)

https://github.com/Tiwarishashwat/InterviewCodes/blob/9b03920957496247991641a0d470bd399bb29a77/TextJustification.java#L10

**Comment by Tiwarishashwat** [comment]
Added the comments for your understanding, I hope it helps :)
